export const alumni = [
  {
    // Hero circular showcase uses `photo` (unchanged)
    name: "Dr. James Whitmore",
    quote: "The credential changed how boardrooms receive me. I walked in as Dr. Whitmore — the room felt it immediately. Fifteen years of work, finally recognised with the title it deserved.",
    credential: "Doctor of Business Administration",
    program: "DBA",
    programLabel: "DBA · ESDST Switzerland",
    role: "CEO, InfraVision India",
    university: "ESDST, Switzerland",
    country: "🇮🇳 India",
    photo: "https://images.unsplash.com/photo-1758691737644-ef8be18256c3?q=80&w=450&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Dr. Levi Bennett",
    quote: "I was sceptical — every 'online doctorate' felt like a shortcut. Techversity showed me the actual accreditation documents before I paid a single rupee. That transparency closed it for me.",
    credential: "Honorary Doctorate",
    program: "Honorary",
    programLabel: "Honorary · Kennedy University",
    role: "Managing Director, FinEdge Group",
    university: "Kennedy University",
    country: "🇦🇪 UAE",
    photo: "https://plus.unsplash.com/premium_photo-1682430145886-39c8decd85fa?q=80&w=450&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Dr. Ahmed Al-Rashid",
    quote: "My advisor didn't disappear after enrolment. She was there through every document, every delay, every question. I have never experienced that level of support from any institution.",
    credential: "PhD, Business Administration",
    program: "PhD",
    programLabel: "PhD · EU Global Malta",
    role: "VP Strategy, Gulf Capital Partners",
    university: "EU Global, Malta",
    country: "🇸🇦 Saudi Arabia",
    photo: "https://images.unsplash.com/photo-1758599543230-652cc6831d69?q=80&w=450&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Dr. Daniel Foster",
    quote: "Within three months of the DBA, two international speaking invitations arrived that I had been chasing for years. The title opens doors that were simply closed before.",
    credential: "Doctor of Business Administration",
    program: "DBA",
    programLabel: "DBA · American Management University",
    role: "Founder, NovaTech Africa",
    university: "American Management University",
    country: "🇳🇬 Nigeria",
    photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=450&q=80",
  },
];

// ── Testimonials section uses THIS (real recipients, founder-provided photos) ──
// `testimonialPhoto` is separate from the Hero showcase `photo` above.
export const testimonials = [
  
  {
    name: "Jan Vitko",
    quote: "I had spent decades in public service and security governance. Techversity did not ask me to prove myself again — they reviewed the record itself, and recognised what was already there.",
    credential: "Honorary PhD · Public Leadership & Security Governance",
    program: "Honorary",
    role: "Public Leadership & Security Governance",
    university: "Kingsley University",
    country: "🇸🇰 Slovakia",
    testimonialPhoto: "/images/testimonial-2.jpeg",
  },
  {
    name: "Thomas Daniel Fuller Jr.",
    quote: "To have a lifetime in ministry recognised with a doctoral title is no small thing. The process was handled with a dignity that matched the work it honoured — careful, formal, and entirely transparent.",
    credential: "Honorary PhD · Divinity & Pastoral Leadership",
    program: "Honorary",
    role: "Pastoral Leader",
    university: "Kingsley University",
    country: "🇺🇸 United States",
    testimonialPhoto: "/images/testimonial-1.jpeg",
  },
  {
    name: "Pierre A. Sawaya",
    quote: "The PhD gave structure to two decades of work in international business and financial technology. Every step was guided personally — I never once felt like a number in a system.",
    credential: "PhD · International Business & Financial Technology",
    program: "PhD",
    role: "International Business & FinTech",
    university: "Kennedy University",
    country: "🇺🇸 United States",
    testimonialPhoto: "/images/testimonial-3.jpeg",
  },
  {
    name: "See Yan Wong",
    quote: "Three recognitions, each earned across a life in education — an Honorary Professorship, an Honorary Doctorate, and a PhD. Techversity shepherded all three with the same unhurried care.",
    credential: "Honorary Professor · Honorary Doctorate · PhD in Education",
    program: "PhD",
    role: "Educator",
    university: "Kingsley University",
    country: "🇭🇰 Hong Kong",
    testimonialPhoto: "/images/testimonial-4.jpeg",
  },
  {
    name: "Caludie Daba",
    quote: "Leadership had always been the thread running through my career, but it took this PhD to give that experience an academic foundation. The guidance I received throughout was thorough and genuinely personal.",
    credential: "PhD · Influence of Leadership Strategies on Firm Competitiveness and Overall Performance",
    program: "PhD",
    role: "Leadership & Firm Performance",
    university: "Kennedy University",
    country: "🇬🇧 United Kingdom",
    testimonialPhoto: "/images/testimonial-5.jpeg",
  },
  {
    name: "Chih-Cheng Wu",
    quote: "Pursuing a DBA later in my career meant I needed a program that respected my time and experience. Kennedy University delivered exactly that — rigorous, but never rigid.",
    credential: "Doctor of Business Administration (DBA)",
    program: "DBA",
    role: "Business Administration",
    university: "Kennedy University",
    country: "🇹🇼 Taiwan",
    testimonialPhoto: "/images/testimonial-6.jpeg",
  },
  {
    name: "Deepak Nayyar",
    quote: "Researching neuroinflammation, the gut microbiome, and neuropsychiatric disorders demands precision at every stage. The support I had made it possible to pursue that precision without compromise.",
    credential: "PhD · Neuroinflammation, Gut Microbiome and Neuropsychiatric Disorders",
    program: "PhD",
    role: "Neuroscience & Microbiome Research",
    university: "Kennedy University",
    country: "🇬🇧 United Kingdom",
    testimonialPhoto: "/images/testimonial-7.jpeg",
  },
  {
    name: "Maria Boutserou",
    quote: "Oral health sits at the intersection of environment and occupation more than people realise. This PhD gave me the platform to explore that intersection properly, with expert guidance at every turn.",
    credential: "PhD in Oral Health within Environmental and Occupational Health",
    program: "PhD",
    role: "Oral Health & Occupational Health",
    university: "Kennedy University",
    country: "🇬🇷 Greece",
    testimonialPhoto: "/images/testimonial-8.jpeg",
  },
];

// Program → colour token map (used by the Testimonials badge)
export const programColors = {
  DBA:      { bg: "#EFF6FF", text: "#2563EB" },
  Honorary: { bg: "#F6EEDB", text: "#9A7320" },
  PhD:      { bg: "#F5F3FF", text: "#7C3AED" },
};