export const posts = [
  {
    slug: "dba-vs-phd",
    category: "Doctorate & PhD",
    categoryColor: "#9A7320",
    title: "DBA vs PhD: Which Doctorate Is Right for Working Professionals?",
    excerpt: "Both carry the title 'Dr.' — but they serve very different careers. We break down the research demands, time commitments, and recognition of each so you can choose with clarity.",
    author: "Techversity Editorial",
    date: "Jun 2026",
    readTime: "12 min read",
    img: "/images/HomePage/Blog/dbavsphd.avif",
    href: "/resources/blog/dba-vs-phd",
    featured: true,
  },
  {
    slug: "honorary-doctorate-guide",
    category: "Accreditation",
    categoryColor: "#2563EB",
    title: "Is an Honorary Doctorate Legitimate? A Complete Guide",
    excerpt: "What it is, what it isn't, and exactly how to verify one before you apply. The guide every serious candidate should read first.",
    author: "Techversity Editorial",
    date: "Jun 2026",
    readTime: "8 min read",
    img: "/images/SharedPrograms/HD.avif",
    href: "/resources/blog/honorary-doctorate-guide",
    featured: false,
  },
  {
    slug: "how-to-choose-accredited-online-university",
    category: "Accreditation",
    categoryColor: "#2563EB",
    title: "How to Choose an Accredited Online University in 2026",
    excerpt: "Not every 'accredited' claim means the same thing. A practical checklist for verifying a university's standing before you apply.",
    author: "Techversity Editorial",
    date: "Jun 2026",
    readTime: "9 min read",
    img: "/images/HomePage/Blog/onlineUniversities.avif",
    href: "/resources/blog/how-to-choose-accredited-online-university",
    featured: false,
  },
  {
    slug: "data-science-certification-skills-employers-want",
    category: "AI & Careers",
    categoryColor: "#7C3AED",
    title: "Top 5 Skills Employers Want from Data Science Certifications",
    excerpt: "Certificates are common. The skills that actually move a hiring decision are not. Here's what recruiters look for beyond the credential.",
    author: "Techversity Editorial",
    date: "Jun 2026",
    readTime: "7 min read",
    img: "/images/HomePage/Blog/skills.avif",
    href: "/resources/blog/data-science-certification-skills-employers-want",
    featured: false,
  },
  {
    slug: "agentic-ai-career-guide",
    category: "AI & Careers",
    categoryColor: "#7C3AED",
    title: "What Is Agentic AI? A Career Guide for 2026",
    excerpt: "From autonomous agents to multi-model pipelines — why this skill is already commanding premium salaries and how to get certified fast.",
    author: "Techversity Editorial",
    date: "Jul 2026",
    readTime: "6 min read",
    img: "/images/Certification/CertificationCard/AgenticAi.avif",
    href: "/resources/blog/agentic-ai-career-guide",
    featured: false,
  },
  {
    slug: "online-mba-roi-mid-career",
    category: "MBA & Master's",
    categoryColor: "#059669",
    title: "Online MBA ROI: Is It Worth It for Mid-Career Professionals?",
    excerpt: "The honest math on what an online MBA costs, what it returns, and who it actually pays off for.",
    author: "Techversity Editorial",
    date: "Jul 2026",
    readTime: "8 min read",
    img: "/images/HomePage/Blog/MBA.avif",
    href: "/resources/blog/online-mba-roi-mid-career",
    featured: false,
  },
  {
    slug: "how-to-verify-university-accreditation",
    category: "Accreditation",
    categoryColor: "#2563EB",
    title: "How to Verify a University's Accreditation Before You Apply",
    excerpt: "A step-by-step method for checking whether a university's accreditation claim holds up — before you commit any time or money.",
    author: "Techversity Editorial",
    date: "Jul 2026",
    readTime: "7 min read",
    img: "/images/HomePage/Blog/accepted.avif",
    href: "/resources/blog/how-to-verify-university-accreditation",
    featured: false,
  },
  {
    slug: "manager-to-doctorate-holder-alumni-stories",
    category: "Career Stories",
    categoryColor: "#DC2626",
    title: "From Manager to Doctorate Holder: Real Alumni Stories",
    excerpt: "What actually changes — professionally and personally — after twenty years of experience becomes a formally recognised doctorate.",
    author: "Techversity Editorial",
    date: "Jul 2026",
    readTime: "10 min read",
    img: "/images/HomePage/Blog/MtoD.avif",
    href: "/resources/blog/manager-to-doctorate-holder-alumni-stories",
    featured: false,
  },
  {
    slug: "cybersecurity-certifications-that-get-you-hired",
    category: "AI & Careers",
    categoryColor: "#7C3AED",
    title: "Cybersecurity Certifications That Actually Get You Hired",
    excerpt: "The market is full of cybersecurity certificates. Here's which ones hiring managers actually recognise — and why.",
    author: "Techversity Editorial",
    date: "Jul 2026",
    readTime: "8 min read",
    img: "/images/Certification/CertificationCard/CyberSecurity.avif",
    href: "/resources/blog/cybersecurity-certifications-that-get-you-hired",
    featured: false,
  },
  {
    slug: "step-by-step-guide-applying-online-doctorate",
    category: "Doctorate & PhD",
    categoryColor: "#9A7320",
    title: "A Step-by-Step Guide to Applying for an Online Doctorate",
    excerpt: "From eligibility check to enrollment confirmation — a clear walk-through of what the online doctorate application process actually involves.",
    author: "Techversity Editorial",
    date: "Jul 2026",
    readTime: "9 min read",
    img: "/images/HomePage/Blog/Steps.avif",
    href: "/resources/blog/step-by-step-guide-applying-online-doctorate",
    featured: false,
  },
];

export const blogCategories = [
  "All",
  "Doctorate & PhD",
  "Accreditation",
  "AI & Careers",
  "MBA & Master's",
  "Career Stories",
];