export const posts = [
  {
    slug: "dba-vs-phd",
    category: "Doctorate & PhD",
    categoryColor: "#9A7320",
    title: "DBA vs PhD: Which Doctorate Is Right for Working Professionals?",
    excerpt: "Both carry the title 'Dr.' — but they serve very different careers. We break down the research demands, time commitments, and recognition of each so you can choose with clarity.",
    author: "Techversity Editorial",
    date: "Jun 2025",
    readTime: "12 min read",
    img: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=700&q=80",
    href: "/resources/blog/dba-vs-phd",
    featured: true,
  },
  {
    slug: "honorary-doctorate-guide",
    category: "Accreditation",
    categoryColor: "#2563EB",
    title: "Is an Honorary Doctorate Legitimate? A Complete Guide",
    excerpt: "What it is, what it isn't, and exactly how to verify one before you apply. The guide every serious candidate should read first.",
    author: "Techversity Editorial",
    date: "May 2025",
    readTime: "8 min read",
    img: "https://images.unsplash.com/photo-1507537297725-24a1c029d3ca?w=700&q=80",
    href: "/resources/blog/honorary-doctorate-guide",
    featured: false,
  },
  {
    slug: "agentic-ai-career-guide",
    category: "AI & Careers",
    categoryColor: "#7C3AED",
    title: "What Is Agentic AI? A Career Guide for 2026",
    excerpt: "From autonomous agents to multi-model pipelines — why this skill is already commanding premium salaries and how to get certified fast.",
    author: "Techversity Editorial",
    date: "Apr 2025",
    readTime: "6 min read",
    img: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=700&q=80",
    href: "/resources/blog/agentic-ai-career-guide",
    featured: false,
  },
];