export const certifications = [
  {
    abbr: "DS",
    field: "Data Science",
    title: "Data Science",
    desc: "Build and deploy production-grade ML models. Python, TensorFlow, scikit-learn — from raw data to live inference.",
    skills: ["Python & Pandas", "Machine Learning", "Neural Networks", "Model Deployment", "Data Wrangling", "Scikit-learn"],
    included: ["Globally recognised certificate", "1-on-1 career advisor", "Resume & LinkedIn review", "Interview preparation"],
    stats: [{ val: "12", unit: "wk", label: "Duration" }, { val: "2,400+", unit: "", label: "Enrolled" }, { val: "94%", unit: "", label: "Completion" }],
    duration: "12 Weeks",
    level: "Intermediate",
    tag: "Most Popular",
    href: "/certifications/data-science",
    accent: "#2563EB", accentBg: "#EFF6FF", accentMid: "#BFDBFE",
    image: "/images/Certification/CertificationCard/DataScience.avif",
  },
  {
    abbr: "AI",
    field: "Artificial Intelligence",
    title: "Agentic AI",
    desc: "LLMs, RAG pipelines, autonomous agents — the fastest-growing skill in tech. Master LangChain, AutoGen, and multi-agent systems.",
    skills: ["Prompt Engineering", "RAG Architecture", "LangChain", "AutoGen", "Agent Design", "LLM Fine-tuning"],
    included: ["Globally recognised certificate", "1-on-1 career advisor", "GitHub portfolio project", "Job referral network"],
    stats: [{ val: "8", unit: "wk", label: "Duration" }, { val: "890+", unit: "", label: "Enrolled" }, { val: "97%", unit: "", label: "Completion" }],
    duration: "8 Weeks",
    level: "Advanced",
    tag: "Trending",
    href: "/certifications/agentic-ai",
    accent: "#7C3AED", accentBg: "#F5F3FF", accentMid: "#DDD6FE",
    image: "/images/Certification/CertificationCard/AgenticAi.avif",
  },
  {
    abbr: "CS",
    field: "Cybersecurity",
    title: "Cybersecurity",
    desc: "Ethical hacking, threat analysis, SOC operations. Build the skills that organisations worldwide can't find enough of.",
    skills: ["Ethical Hacking", "Threat Modelling", "SOC Operations", "Pen Testing", "Security Audits", "SIEM Tools"],
    included: ["Globally recognised certificate", "1-on-1 career advisor", "CTF lab access", "Industry mentorship"],
    stats: [{ val: "10", unit: "wk", label: "Duration" }, { val: "1,100+", unit: "", label: "Enrolled" }, { val: "92%", unit: "", label: "Completion" }],
    duration: "10 Weeks",
    level: "Intermediate",
    tag: null,
    href: "/certifications/cybersecurity",
    accent: "#DC2626", accentBg: "#FEF2F2", accentMid: "#FECACA",
    image: "/images/Certification/CertificationCard/CyberSecurity.avif",
  },
  {
    abbr: "DA",
    field: "Data & Business Intelligence",
    title: "Data Analytics",
    desc: "SQL, Power BI, Tableau — transform raw data into boardroom-ready insight. No prior coding background required.",
    skills: ["SQL & Excel", "Power BI", "Tableau", "Statistical Analysis", "Dashboard Design", "Data Storytelling"],
    included: ["Globally recognised certificate", "1-on-1 career advisor", "Capstone project", "Placement assistance"],
    stats: [{ val: "8", unit: "wk", label: "Duration" }, { val: "3,200+", unit: "", label: "Enrolled" }, { val: "96%", unit: "", label: "Completion" }],
    duration: "8 Weeks",
    level: "Beginner",
    tag: null,
    href: "/certifications/data-analytics",
    accent: "#059669", accentBg: "#ECFDF5", accentMid: "#A7F3D0",
    image: "/images/Certification/CertificationCard/DataAnalytics.avif",
  },
  {
    abbr: "CC",
    field: "Cloud Infrastructure",
    title: "Cloud Computing",
    desc: "AWS, Azure, GCP — architect, deploy and manage enterprise cloud at scale. Exam-aligned with major cloud certifications.",
    skills: ["AWS & Azure", "GCP", "Cloud Architecture", "DevOps & CI/CD", "Kubernetes", "Cost Optimisation"],
    included: ["Globally recognised certificate", "1-on-1 career advisor", "Cloud lab credits", "Exam prep materials"],
    stats: [{ val: "10", unit: "wk", label: "Duration" }, { val: "1,800+", unit: "", label: "Enrolled" }, { val: "93%", unit: "", label: "Completion" }],
    duration: "10 Weeks",
    level: "Intermediate",
    tag: null,
    href: "/certifications/cloud-computing",
    accent: "#0891B2", accentBg: "#ECFEFF", accentMid: "#A5F3FC",
    image: "/images/Certification/CertificationCard/CloudComputing.avif",
  },
  {
    abbr: "PM",
    field: "Project Management",
    title: "Project Management",
    desc: "PMP-aligned curriculum for modern project leaders. Agile, Scrum, and traditional methodologies — all in six focused weeks.",
    skills: ["Agile & Scrum", "Risk Management", "Stakeholder Comms", "PMP Prep", "Budgeting", "Project Lifecycle"],
    included: ["Globally recognised certificate", "1-on-1 career advisor", "PMP exam guide", "Alumni network access"],
    stats: [{ val: "6", unit: "wk", label: "Duration" }, { val: "4,100+", unit: "", label: "Enrolled" }, { val: "98%", unit: "", label: "Completion" }],
    duration: "6 Weeks",
    level: "All Levels",
    tag: null,
    href: "/certifications/project-management",
    accent: "#9A7320", accentBg: "#FEFCE8", accentMid: "#FDE68A",
    image: "/images/Certification/CertificationCard/ProjectManagement.avif",
  },
];