export const programs = [
  {
    id: 1, slug: "dba-esdst", initials: "ES",
    badgeBg: "#D9A441", badgeText: "#0B2545",
    logo: "https://pbs.twimg.com/profile_images/1593833120440238080/jo7eRmrs_400x400.jpg",
    partnerLogos: [
      { logo: "https://pbs.twimg.com/profile_images/1593833120440238080/jo7eRmrs_400x400.jpg", name: "ESDST", country: "🇫🇷 France" },
      { logo: "https://www.qahe.org.uk/wp-content/uploads/2023/11/Kennedy-University-520-x-330.jpg", name: "Kennedy", country: "🇺🇸 USA" },
      { logo: "https://euroasianuniversity.ee/wp-content/uploads/2025/04/eau_logo-240x240-1-2.png", name: "Euro-Asian", country: "🇰🇿 Kazakhstan" },
    ],
    title: "Doctor of Business Administration",
    university: "ESDST University", country: "France", flag: "🇫🇷",
    desc: "Applied doctoral research for senior executives — no career break required.",
    forWho: "Senior executives, 10+ years experience",
    outcome: "Doctoral title · Board credibility · Research authority",
    level: "Doctorate", duration: "18 Months", mode: "Online", fee: "From $8,000",
    category: "doctorate",
  },
  {
    id: 2, slug: "phd-kennedy", initials: "KU",
    badgeBg: "#0B2545", badgeText: "#ffffff",
    logo: "https://www.qahe.org.uk/wp-content/uploads/2023/11/Kennedy-University-520-x-330.jpg",
    partnerLogos: [
      { logo: "https://www.qahe.org.uk/wp-content/uploads/2023/11/Kennedy-University-520-x-330.jpg", name: "Kennedy", country: "🇺🇸 USA" },
      { logo: "https://pbs.twimg.com/profile_images/1593833120440238080/jo7eRmrs_400x400.jpg", name: "ESDST", country: "🇫🇷 France" },
    ],
    title: "PhD in Business Management",
    university: "Kennedy University", country: "USA", flag: "🇺🇸",
    desc: "Research-intensive doctoral pathway with dissertation support and faculty mentorship.",
    forWho: "Academics & researchers seeking scholarly credentials",
    outcome: "PhD title · Published research · Academic standing",
    level: "PhD", duration: "24 Months", mode: "Online", fee: "From $10,000",
    category: "doctorate",
  },
  {
    id: 3, slug: "honorary-doctorate", initials: "HD",
    badgeBg: "#D9A441", badgeText: "#0B2545",
    logo: "https://www.qahe.org.uk/wp-content/uploads/2023/11/Kennedy-University-520-x-330.jpg",
    partnerLogos: [
      { logo: "https://www.qahe.org.uk/wp-content/uploads/2023/11/Kennedy-University-520-x-330.jpg", name: "Kennedy", country: "🇺🇸 USA" },
      { logo: "https://pbs.twimg.com/profile_images/1593833120440238080/jo7eRmrs_400x400.jpg", name: "ESDST", country: "🇫🇷 France" },
      { logo: "https://euroasianuniversity.ee/wp-content/uploads/2025/04/eau_logo-240x240-1-2.png", name: "Euro-Asian", country: "🇰🇿 Kazakhstan" },
      { logo: "https://i.pinimg.com/736x/eb/44/78/eb4478132393460e5ca320ff3b05f983.jpg", name: "SBS Swiss", country: "🇨🇭 Switzerland" },
    ],
    title: "Honorary Doctorate",
    university: "Multiple Partner Universities", country: "Global", flag: "🌍",
    desc: "Formal recognition of professional achievement — issued by accredited partner universities.",
    forWho: "Distinguished leaders with 15+ years of impact",
    outcome: "Honorary Dr. title · Institutional recognition · Prestige",
    level: "Honorary", duration: "6–12 Months", mode: "Online", fee: "From $5,000",
    category: "doctorate",
  },
  {
    id: 4, slug: "mba-global", initials: "MB",
    badgeBg: "#21385C", badgeText: "#ffffff",
    logo: "https://th.bing.com/th/id/OIP.h0LszIa1aPlUxM0kzvkZewHaCi?w=289&h=120&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
    partnerLogos: [
      { logo: "https://th.bing.com/th/id/OIP.h0LszIa1aPlUxM0kzvkZewHaCi?w=289&h=120&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3", name: "EU Global", country: "🇲🇹 Malta" },
      { logo: "https://i.pinimg.com/736x/eb/44/78/eb4478132393460e5ca320ff3b05f983.jpg", name: "SBS Swiss", country: "🇨🇭 Switzerland" },
      { logo: "https://euroasianuniversity.ee/wp-content/uploads/2025/04/eau_logo-240x240-1-2.png", name: "Euro-Asian", country: "🇰🇿 Kazakhstan" },
    ],
    title: "MBA — Global Executive Track",
    university: "EU Global Institute", country: "Malta", flag: "🇲🇹",
    desc: "Internationally recognized MBA for mid-career professionals targeting leadership roles.",
    forWho: "Mid-career professionals targeting leadership",
    outcome: "MBA credential · Global network · Leadership toolkit",
    level: "Master's", duration: "12 Months", mode: "Online", fee: "From $6,500",
    category: "masters",
  },
  {
    id: 5, slug: "msc-data-science", initials: "DS",
    badgeBg: "#16263D", badgeText: "#D9A441",
    logo: "https://i.pinimg.com/736x/eb/44/78/eb4478132393460e5ca320ff3b05f983.jpg",
    partnerLogos: [
      { logo: "https://i.pinimg.com/736x/eb/44/78/eb4478132393460e5ca320ff3b05f983.jpg", name: "SBS Swiss", country: "🇨🇭 Switzerland" },
      { logo: "https://th.bing.com/th/id/OIP.h0LszIa1aPlUxM0kzvkZewHaCi?w=289&h=120&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3", name: "EU Global", country: "🇲🇹 Malta" },
    ],
    title: "MSc in Data Science",
    university: "SBS Swiss Business School", country: "Switzerland", flag: "🇨🇭",
    desc: "Graduate-level data science degree covering ML, AI, and analytics with industry projects.",
    forWho: "Tech professionals upskilling to data leadership",
    outcome: "MSc degree · Data science expertise · Career pivot",
    level: "Master's", duration: "18 Months", mode: "Online", fee: "From $7,000",
    category: "masters",
  },
  {
    id: 6, slug: "executive-mba", initials: "EM",
    badgeBg: "#D9A441", badgeText: "#0B2545",
    logo: "https://euroasianuniversity.ee/wp-content/uploads/2025/04/eau_logo-240x240-1-2.png",
    partnerLogos: [
      { logo: "https://euroasianuniversity.ee/wp-content/uploads/2025/04/eau_logo-240x240-1-2.png", name: "Euro-Asian", country: "🇰🇿 Kazakhstan" },
      { logo: "https://th.bing.com/th/id/OIP.h0LszIa1aPlUxM0kzvkZewHaCi?w=289&h=120&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3", name: "EU Global", country: "🇲🇹 Malta" },
      { logo: "https://pbs.twimg.com/profile_images/1593833120440238080/jo7eRmrs_400x400.jpg", name: "ESDST", country: "🇫🇷 France" },
    ],
    title: "Executive MBA (Fast-Track)",
    university: "Euro-Asian University", country: "Kazakhstan", flag: "🇰🇿",
    desc: "Designed for C-suite and VP-level professionals seeking global MBA credentials fast.",
    forWho: "C-suite & VP-level professionals",
    outcome: "EMBA credential · Executive network · Fast-track",
    level: "Executive", duration: "8 Months", mode: "Online", fee: "From $9,000",
    category: "executive",
  },
  {
    id: 7, slug: "agentic-ai", initials: "AI",
    badgeBg: "#0B2545", badgeText: "#D9A441",
    logo: "https://th.bing.com/th/id/OIP.h0LszIa1aPlUxM0kzvkZewHaCi?w=289&h=120&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
    partnerLogos: [
      { logo: "https://th.bing.com/th/id/OIP.h0LszIa1aPlUxM0kzvkZewHaCi?w=289&h=120&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3", name: "EU Global", country: "MT MALTA" },
    ],
    title: "Agentic AI & Automation Mastery",
    university: "EU Global", country: "Global", flag: "🌐",
    desc: "Build AI agents, automate workflows, and deploy real projects in a 4-month applied program.",
    forWho: "Professionals ready to move beyond prompts",
    outcome: "AI practitioner · Automation builder · Future-ready",
    level: "Certification", duration: "4 Months", mode: "Online", fee: "From $999",
    category: "certifications",
  },
  {
    id: 8, slug: "data-science-cert", initials: "DS",
    badgeBg: "#21385C", badgeText: "#ffffff",
    logo: "https://th.bing.com/th/id/OIP.h0LszIa1aPlUxM0kzvkZewHaCi?w=289&h=120&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
    partnerLogos: [
      { logo: "https://th.bing.com/th/id/OIP.h0LszIa1aPlUxM0kzvkZewHaCi?w=289&h=120&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3", name: "EU Global", country: "MT MALTA" },
    ],
    title: "Data Science Certification",
    university: "EU Global", country: "Global", flag: "🌐",
    desc: "Industry-recognized certification covering Python, ML, SQL, and Power BI.",
    forWho: "Analysts & engineers entering data science",
    outcome: "Certified data scientist · Job-ready skills",
    level: "Certification", duration: "3 Months", mode: "Online", fee: "From $699",
    category: "certifications",
  },
  {
    id: 9, slug: "cybersecurity", initials: "CS",
    badgeBg: "#D9A441", badgeText: "#0B2545",
    logo: "https://th.bing.com/th/id/OIP.h0LszIa1aPlUxM0kzvkZewHaCi?w=289&h=120&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
    partnerLogos: [
      { logo: "https://th.bing.com/th/id/OIP.h0LszIa1aPlUxM0kzvkZewHaCi?w=289&h=120&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3", name: "EU Global", country: "MT MALTA" },
    ],
    title: "Cybersecurity Mastery",
    university: "EU Global", country: "Global", flag: "🌐",
    desc: "Hands-on training covering ethical hacking, cloud security, and SOC operations.",
    forWho: "IT professionals targeting security roles",
    outcome: "Security certified · SOC-ready · Career switch",
    level: "Certification", duration: "3 Months", mode: "Online", fee: "From $799",
    category: "certifications",
  },
];

export const tabs = [
  { label: "All Programs",   value: "all",            bg: "#FAF8F4" },
  { label: "Doctorate",      value: "doctorate",      bg: "#E8E3DA" },
  { label: "Master's",       value: "masters",        bg: "#EDE8DF" },
  { label: "Executive Ed",   value: "executive",      bg: "#F0EBE1" },
  { label: "Certifications", value: "certifications", bg: "#FAF8F4" },
];