export const programs = [
  // ── DOCTORATE ──
  {
    id: 1, slug: "dba-esdst", initials: "ES",
    badgeBg: "#D9A441", badgeText: "#0B2545",
    title: "Doctor of Business Administration",
    university: "ESDST University", country: "France", flag: "🇫🇷", code: "fr",
    desc: "Applied doctoral research for senior executives — no career break required.",
    forWho: "Senior executives, 10+ years experience",
    outcome: "Doctoral title · Board credibility · Research authority",
    level: "Doctorate", duration: "18 Months", mode: "Online", fee: "From $8,000",
    category: "doctorate",
    image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&q=80",
  },
  {
    id: 2, slug: "phd-kennedy", initials: "KU",
    badgeBg: "#0B2545", badgeText: "#ffffff",
    title: "PhD in Business Management",
    university: "Kennedy University", country: "USA", flag: "🇺🇸", code: "us",
    desc: "Research-intensive doctoral pathway with dissertation support and faculty mentorship.",
    forWho: "Academics & researchers seeking scholarly credentials",
    outcome: "PhD title · Published research · Academic standing",
    level: "PhD", duration: "24 Months", mode: "Online", fee: "From $10,000",
    category: "doctorate",
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80",
  },
  {
    id: 3, slug: "honorary-doctorate", initials: "HD",
    badgeBg: "#D9A441", badgeText: "#0B2545",
    title: "Honorary Doctorate",
    university: "Multiple Partner Universities", country: "Global", flag: "🌍", code: "un",
    desc: "Formal recognition of professional achievement — issued by accredited partner universities.",
    forWho: "Distinguished leaders with 15+ years of impact",
    outcome: "Honorary Dr. title · Institutional recognition · Prestige",
    level: "Honorary", duration: "6–12 Months", mode: "Online", fee: "From $5,000",
    category: "doctorate",
    image: "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=800&q=80",
  },
  {
    id: 4, slug: "honorary-professorship", initials: "HP",
    badgeBg: "#D9A441", badgeText: "#0B2545",
    title: "Honorary Professorship",
    university: "Multiple Partner Universities", country: "Global", flag: "🌍", code: "un",
    desc: "Formal academic recognition of professional expertise — issued by accredited partner universities.",
    forWho: "Distinguished professionals with significant industry or academic contribution",
    outcome: "Honorary Professor title · Institutional recognition · Prestige",
    level: "Honorary", duration: "6–12 Months", mode: "Online", fee: "From $5,000",
    category: "doctorate",
    image: "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=800&q=80",
  },

  // ── MASTER'S ──
  {
    id: 5, slug: "masters", initials: "MA",
    badgeBg: "#21385C", badgeText: "#ffffff",
    title: "Master's Degree",
    university: "Multiple Partner Universities", country: "Global", flag: "🌍", code: "un",
    desc: "Internationally recognized graduate degrees for mid-career professionals targeting leadership roles.",
    forWho: "Mid-career professionals deepening expertise",
    outcome: "Master's credential · Global network · Leadership toolkit",
    level: "Master's", duration: "12–18 Months", mode: "Online", fee: "From $6,500",
    category: "masters",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
  },

  // ── BACHELOR'S ──
  {
    id: 6, slug: "bachelors", initials: "BA",
    badgeBg: "#16263D", badgeText: "#D9A441",
    title: "Bachelor's Degree",
    university: "Multiple Partner Universities", country: "Global", flag: "🌍", code: "un",
    desc: "Internationally accredited undergraduate degrees for working professionals and early-career learners.",
    forWho: "Working professionals & early-career learners",
    outcome: "Bachelor's credential · Global recognition · Career foundation",
    level: "Bachelor's", duration: "24–36 Months", mode: "Online", fee: "From $4,500",
    category: "bachelors",
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80",
  },

  // ── CERTIFICATIONS (kept for homepage tabs / other use) ──
  {
    id: 7, slug: "agentic-ai", initials: "AI",
    badgeBg: "#0B2545", badgeText: "#D9A441",
    title: "Agentic AI & Automation Mastery",
    university: "Techversity.ai", country: "Global", flag: "🌐", code: "un",
    desc: "Build AI agents, automate workflows, and deploy real projects in a 4-month applied program.",
    forWho: "Professionals ready to move beyond prompts",
    outcome: "AI practitioner · Automation builder · Future-ready",
    level: "Certification", duration: "4 Months", mode: "Online", fee: "From $999",
    category: "certifications",
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80",
  },
  {
    id: 8, slug: "data-science-cert", initials: "DS",
    badgeBg: "#21385C", badgeText: "#ffffff",
    title: "Data Science Certification",
    university: "Techversity.ai", country: "Global", flag: "🌐", code: "un",
    desc: "Industry-recognized certification covering Python, ML, SQL, and Power BI.",
    forWho: "Analysts & engineers entering data science",
    outcome: "Certified data scientist · Job-ready skills",
    level: "Certification", duration: "3 Months", mode: "Online", fee: "From $699",
    category: "certifications",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
  },
  {
    id: 9, slug: "cybersecurity", initials: "CS",
    badgeBg: "#D9A441", badgeText: "#0B2545",
    title: "Cybersecurity Mastery",
    university: "Techversity.ai", country: "Global", flag: "🌐", code: "un",
    desc: "Hands-on training covering ethical hacking, cloud security, and SOC operations.",
    forWho: "IT professionals targeting security roles",
    outcome: "Security certified · SOC-ready · Career switch",
    level: "Certification", duration: "3 Months", mode: "Online", fee: "From $799",
    category: "certifications",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80",
  },
];

export const tabs = [
  { label: "All Programs",   value: "all",            bg: "#FAF8F4" },
  { label: "Doctorate",      value: "doctorate",      bg: "#E8E3DA" },
  { label: "Master's",       value: "masters",        bg: "#EDE8DF" },
  { label: "Bachelor's",     value: "bachelors",      bg: "#F0EBE1" },
  { label: "Certifications", value: "certifications", bg: "#FAF8F4" },
];

export const degreeCategories = [
  {
    value: "doctorate",
    label: "Doctorate",
    tagline: "The highest credential a career can carry — PhD, DBA, and Honorary.",
    accent: "#16263D",
  },
  {
    value: "masters",
    label: "Master's",
    tagline: "Graduate degrees that deepen expertise and open leadership roles.",
    accent: "#21385C",
  },
  {
    value: "bachelors",
    label: "Bachelor's",
    tagline: "Accredited undergraduate degrees built for working professionals.",
    accent: "#9A7320",
  },
];